version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - 8000:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    container_name: app_nginx
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
    - ./:/var/www
    depends_on:
      - db
    container_name: php

  db:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    volumes:
    - ./tmp/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: "test-api"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    container_name: db

